import type { FC, ReactNode } from 'react'
import Head from 'next/head'
import { Header } from '@/components/layouts/Header'

type Props = {
  title: string
  children: ReactNode
}

export const Layout: FC<Props> = ({ children, title = 'T3 Todo' }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container mx-auto flex min-h-full flex-col items-center justify-center p-8">
        {children}
      </main>
    </>
  )
}
